services:
  sgtm:
    image: gcr.io/cloud-tagging-10302018/gtm-cloud-image:stable
    container_name: sgtm_server
    restart: always
    environment:
      CONTAINER_CONFIG: '${SGTM_CONTAINER_CONFIG}'
      RUN_AS_PREVIEW_SERVER: '${RUN_AS_PREVIEW_SERVER:-true}'
    ports:
      - "${SGTM_PORT:-8080}:8080"
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
